### PR TITLE
Playstation buttons and translations minor corrections

### PR DESCRIPTION
**Pull request by NicolasR**
Hello,

I added Playstation buttons on screen when compiling for vita.
I corrected some missing translations too.

My last pull on this game i think.

### CODE REVIEW

**Comment by NicolasR** [comment]
Could you explain how to proceed ?

**Comment by usineur** [comment]
On your repo:

```
git checkout -b usineur-vita vita
git pull https://github.com/usineur/ZeldaROTH.git vita
```

Btw, i "merged" your modifications: b9c9b9f and 884db46

**Comment by NicolasR** [comment]
Ok thanks.

**Comment by NicolasR** [comment]
Is there a way I can contact you directly instead of github ?

**Comment by usineur** [comment]
You can send me a PM on gbatemp, user: usineur0

**Pull request closed without merging**
